server:
  port: 9000

spring:
  application:
    name: test-spring-security

  #======begin============== Druid 数据库连接池 ============================
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test_spring_security?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: debug572750
      driver-class-name: com.mysql.cj.jdbc.Driver

      #连接池配置（通常只需要修改 initialSize、minIdle、maxActive）
      initial-size: 3
      max-active: 10
      minIdle: 1
      #获取连接超时时间
      max-wait: 3000
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存时间，单位毫秒
      min-evictable-idle-time-millis: 300000
      #配置过滤器，stat用于监控，wall用于防SQL注入
      filters: stat,wall

      #===== statFilter 配置 =====
      web-stat-filter.enabled: true
      web-stat-filter.url-pattern: /*
      web-stat-filter.exclusions: "*.js, *css, *.jpg, *.png, *gif, *ico, /druid/*"
      web-stat-filter.session-stat-max-count: 100
      web-stat-filter.profile-enable: true
      #StatViewServlet配置
      #展示Druid的统计信息，StatViewServlet的用途包括: 1.提供监控信息展示的html页面2.提供监控信息的JSON API
      stat-view-servlet.enabled: true
      #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html
      #http://localhost:8082/druid/index.html
      stat-view-servlet.url-pattern: /druid/*
      #允许清空数据
      stat-view-servlet.reset-enable: true
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin
      #StatViewSerlvet展示出来的监控信息比较敏感，是系统运行的内部情况，如果你需要做访问控制，可以配置allow和deny这两个参数
      #deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
      #配置的格式
      #<IP>
      #或者<IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
      #24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。
      stat-view-servlet.allow: 127.0.0.1/24
      #stat-view-servlet.deny=128.242.127.1/24,128.242.128.1
      #Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      #aop-patterns= # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
  #======end============== Druid 数据库连接池 ============================

  #======begin=================== mybatis 配置 ============================
  # 分页插件
  pagehelper:
    supportMethodsArguments: true
    reasonable: false
    helperDialect: mysql
    params: count=countSql

#  mybatis:
#    #  mybatis-plus:
#    executor-type: reuse
#    configuration:
#      cache-enabled: false
#    type-aliases-package: ind.vijay.demo.bean
#    mapper-locations: classpath*:ind/vijay/demo/mapper/*.xml
#    global-config:
#      db-config:
#        field-strategy: default
#        id-type: auto
#      banner: false
  #======end=================== mybatis 配置 ============================

  #======start=================== mvc 配置 ============================
  mvc:
    favicon:
      enabled: false    #关闭浏览器的标签
  #======end=================== mvc 配置 ============================

  #logpack日志配置
  logging:
    level:
      com:
        su:
          gamemng:
            dao: debug
    config: classpath:logpack.xml

mybatis:
  type-aliases-package: ind.vijay.demo.bean
  mapper-locations: classpath*:ind/vijay/demo/mapper/*.xml
  global-config:
    db-config:
      field-strategy: default
      id-type: auto
    banner: false